djnotes/urls.py
from django.contrib import admin
from django.urls import path, include
from djnotes.views import home_view

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', home_view, name='home'),
    path('notes/', include('notes.urls', namespace='notes')),
]

notes/urls.py
from django.contrib import admin
from django.urls import path, include
from notes.views import *
from django.contrib.auth import views as authViews


app_name = 'notes'

urlpatterns = [
    path('', index_view, name='index'),
    path('addnote/', add_note, name='addnote'),
    path('addtag/', add_tag, name='addtag'),
    # path('savetag/', save_tag, name='savetag'),
    path('tags/<int:id>', tag_search, name='tagsearch'),
    path('logout/', authViews.LogoutView.as_view(template_name="exit.html"), name='logout'),
    # path('logout/', 'django.contrib.auth.logout', {'next_page': 'home'}, name='logout'),
]

notes/models.py
from django.db import models


class Note(models.Model):
    label = models.CharField(max_length=200, verbose_name="Заголовок заметки")
    body = models.TextField(verbose_name="Текст заметки")
    timestamp = models.DateTimeField(auto_now_add=True)
    tags = models.ManyToManyField('Tag', related_name='notes', blank = True, verbose_name="Теги", error_messages={'invalid':'Enter a valid phone number'})

    # def __unicode__(self):
    #     return self.label


class Tag(models.Model):
    label = models.CharField(max_length=200, verbose_name="Тег", unique=True)

    class Meta:
        ordering = ['label',]

    def __str__(self):
        return self.label

    def __unicode__(self):
        return self.label

notes/forms.py
from django import forms
from notes.models import Note, Tag

class NoteForm(forms.ModelForm):
    class Meta:
        model = Note
        fields = ('label', 'body', 'tags')


    def __init__(self, *args, **kwargs):
        super(NoteForm, self).__init__(*args, **kwargs)  # Call to ModelForm constructor
        self.fields['tags'].widget.attrs['style'] = 'height: 200px;'

class TagForm(forms.ModelForm):
    class Meta:
        model = Tag
        fields = ('label', )

djnotes/views.py
from django.shortcuts import render
from django.urls import reverse
from django.contrib import messages
from django.contrib.auth import authenticate, login
from django.http import HttpResponseRedirect


def home_view(request):
    if request.method == 'POST':
        username = request.POST.get('username', None)
        password = request.POST.get('password', None)

        auth = authenticate(username=username, password=password)
        if auth is not None:
            login(request, auth)
            return HttpResponseRedirect(reverse('notes:index'))
        else:
            messages.add_message(request, messages.INFO, "Не удалось авторизоваться!")
            return HttpResponseRedirect(reverse('home'))

    if not request.user.is_authenticated:
        return render(request, 'home.html')
    else:
        return HttpResponseRedirect(reverse('notes:index'))

notes/views.py
from django.shortcuts import render, get_object_or_404
from django.contrib import messages
from django.urls import reverse
from django.http import HttpResponseRedirect
from notes.models import Note, Tag
from notes.forms import NoteForm, TagForm
from django.contrib.auth.decorators import user_passes_test
from django.core.paginator import Paginator
from django.forms.utils import ErrorList


class DivErrorList(ErrorList):
     def __str__(self):              # __unicode__ on Python 2
         return self.as_divs()
     def as_divs(self):
         if not self: return ''
         return '<div class="errorlist">%s</div>' % ''.join(['<div class="error">%s</div>' % e for e in self])


def authuser_only(user):
    return (user.is_authenticated)


@user_passes_test(authuser_only, login_url="/")
def add_note(request):
    id = request.GET.get('id', None)
    if id is not None:
        note = get_object_or_404(Note, id=id)
    else:
        note = None

    if request.method == 'POST':
        if request.POST.get('control') == 'delete':
            note.delete()
            messages.add_message(request, messages.INFO, 'Заметка удалена!')
            return HttpResponseRedirect(reverse('notes:index'))

        form = NoteForm(request.POST, instance=note)
        if form.is_valid():
            form.save()
            messages.add_message(request, messages.INFO, 'Заметка добавлена!')
            return HttpResponseRedirect(reverse('notes:index'))

    else:
        form = NoteForm(instance=note)

    return render(request, 'notes/addnote.html', {'form': form, 'note': note})


def add_tag(request):
    id = request.GET.get('id', None)
    if id is not None:
        tag = get_object_or_404(Tag, id=id)
    else:
        tag = None

    if request.method == 'POST':

        #временно убираю возможность удаления тега. Не придумал, куда прикрутить
        # if request.POST.get('control') == 'delete':
        #     tag.delete()
        #     messages.add_message(request, messages.INFO, 'Тег удалён!')
        #     return HttpResponseRedirect(reverse('notes:index'))

        form = TagForm(request.POST, instance=tag, error_class=DivErrorList)

        if form.is_valid():
            t = form.save(commit=False)
            t.save()
            messages.add_message(request, messages.INFO, 'Тег добавлен!')
        else:
            messages.add_message(request, messages.INFO, 'Ошибка! Тег уже существует!')
            print(form.errors)
        return HttpResponseRedirect(reverse('notes:addnote'))

    else:
        form = TagForm(instance=tag)

    return render(request, 'notes/newtag.html', {'form': form, 'tag': tag})

@user_passes_test(authuser_only, login_url="/")
def tag_search(request, **kwargs):
    id = kwargs['id']
    tag = get_object_or_404(Tag, id=id)
    notes_all = tag.notes.all()
    paginator = Paginator(notes_all, 2)
    page = request.GET.get('page')
    notes = paginator.get_page(page)
    data = {
        'notes': notes,
        'tag': tag,
        'title': 'Заметки по тегу "'+ tag.label + '"'
    }
    return render(request, 'notes/tagsearch.html', data)


@user_passes_test(authuser_only, login_url="/")
def index_view(request):
    notes_all =  Note.objects.all().order_by('-timestamp')
    paginator = Paginator(notes_all, 5)
    page = request.GET.get('page')
    notes = paginator.get_page(page)
    data = {
        'notes': notes,
        'tags': Tag.objects.all().order_by('label'),
        'title': 'DjNote. Заметки'
    }
    return render(request, 'notes/index.html', data)

templates/base.html
{% load staticfiles %}
<head>
    <title>{% block title %}{% endblock title %}</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
    <link rel="stylesheet" href="{% static 'css/main.css' %}"/>
    <script src="{% static 'js/jquery-3.4.0.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
</head>

<body>

{# Шапка сайта #}
<nav class="navbar fixed-top navbar-expand-lg navbar-dark bg-dark">
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
                <a class="nav-link" href="{% url 'home' %}">Главная</a>
            </li>
        </ul>
    </div>

    <div class="navbar-nav">
        {% if user.is_authenticated %}
            <div class="dropdown show mr-3">
                <a class="btn btn-secondary dropdown-toggle" href="#" role="button" id="dropdownMenuLink"
                   data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    {{ user.get_username }}
                </a>

                <div class="dropdown-menu" aria-labelledby="dropdownMenuLink">
                    <a class="dropdown-item" href="{% url 'notes:index' %}">Просмотреть свои заметки</a>
                    <a class="dropdown-item" href="{% url 'notes:logout' %}">Выйти из системы</a>
                </div>
            </div>
        {% endif %}
        <a href="{% url 'notes:addnote' %}" class="btn btn-info mr-2">Добавить заметку</a>

    </div>
</nav>
{# Конец шапки сайта #}

<div class="contaiter UnderFooter">

    {# блок с сообщениями #}
    {% if messages %}
        <div class="container">
            <div class="messages">
                {% for message in messages %}
                    <div id="message_{{ forloop.counter }}"
                            {% if message.tags %} class="alert alert-{{ message.tags }}"{% endif %}>
                        {{ message }}
                    </div>
                {% endfor %}
            </div>
        </div>
    {% endif %}

    <div class="container">
        {% block body %}{% endblock body %}
    </div>

    <hr>

    {% block footer %}
        <div class="container">
            <footer>
                <p class="pull-right"><a href="#">Пролистать страницу наверх</a></p>
            </footer>
        </div>
    {% endblock footer %}

</div>

</body>
</html>

templates/exit.html
{% extends 'base.html' %}
{% load static %}
{% block body %}

    <div class="form-section">
        <h2>Вы успешно вышли с аккаунта</h2>
    </div>

    <a href="{% url 'home' %}">Войти в личный кабинет снова</a>

{% endblock body %}

templates/home.html
{% extends 'base.html' %}
{% load static %}
{% block body %}

<div class="jumbotron">
    <h1 align='center'>Вход в систему</h1>
    <div class='container' style='padding-top:10px'>
        <form action="" method="post">{% csrf_token %}
            <div class="row">
                <div class="col-md-6">
                    <input type='text' id='id_username' name='username' class='form-control'
                           placeholder='Username'/>
                </div>
                <div class='col-md-6'>
                    <input type='password' id='id_password' name='password' class='form-control'
                           placeholder='Password'/>
                </div>
            </div>
            <br>
            <input type="submit" value="Login" class='btn btn-primary btn-lg btn-block'/>
        </form>
    </div>
</div>

{% endblock body %}

templates/notes/addnote.html
{% extends 'notes/../base.html' %}
{% load static %}

{% block body %}

    <h1 align='center'>{% if note %} Изменение заметки {% else %} Создание новой заметки {% endif %}</h1>


    <form action="" method="post">{% csrf_token %}
        {{ form.as_p }}

        <div class="row mb-4">
            <div class="col">
                <a href="#" class="btn btn-sm btn-info add_tag" data-toggle="modal" data-target="#basicModal"
                   data-url="{% url 'notes:addtag' %}">Добавить тег</a>
            </div>
        </div>


        <input type='submit' value=
                {% if note %}
                    'Изменить заметку'
                {% else %}
                    'Создать заметку'
                {% endif %}
        class='btn btn-primary btn-lg btn-block' />
    </form>

    {% if note %}
        <div class="col-md-12" style="padding-top:15px; padding-left: 0px; padding-right: 0px">
            <form action="" method="POST">{% csrf_token %}
                <input type="hidden" name="control" value="delete"/>
                <input type="submit" value="Удалить заметку" class="btn btn-lg btn-block btn-danger"/>
            </form>
        </div>
    {% endif %}

    <!-- basic modal -->
    <div class="modal fade" id="basicModal" tabindex="-1" role="dialog" aria-labelledby="basicModal" aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">


                </div>
            </div>
        </div>
    </div>


    <script type='text/javascript'>
        $('input[type="text"]').addClass('form-control');
        $('textarea').addClass('form-control');
        $('select').addClass('form-control');

        $(".add_tag").on("click", function () {
            $.ajax({
                url: $(this).attr("data-url"),
                success: function (data) {
                    $(".modal-body").html(data);
                }
            });
        });

        $('#basicModal').on('shown.bs.modal', function () {
            setTimeout(function () {
                $('#tag_edit').focus();
            }, 100);
        })

    </script>


{% endblock body %}

templates/notes/addtag.html
{% extends 'base.html' %}
{% load static %}

{% block body %}

    {% include 'notes/newtag.html' %}

{% endblock body %}

templates/notes/index.html
{# главная страница со списком статей #}

{% extends '../base.html' %}
{% load static %}

{% block title %}
    {{ title }}
{% endblock title %}

{% block body %}

    <div class="row">

        {# колонка со статьями #}
        <div class='col-md-9'>

            <div class="alert alert-primary text-center" role="alert">
                <h1>Заметки</h1>
            </div>

            <a href="{% url 'notes:addnote' %}" class="btn btn-info mb-3">Добавить заметку</a>

            {% if notes %}

                {% include 'notes/notelist.html' with notes=notes %}

            {% else %}

                <div class='alert alert-warning' align='center'>
                    <h3>Заметки ещё не созданы</h3>
                </div>
                <a href="{% url 'notes:addnote' %}" class="btn btn-outline-secondary mr-2">Добавить заметку</a>

            {% endif %}

        </div>

        {# колонка со тегами #}
        <div class='col-md-3'>
            {% include 'notes/taglist.html' with tags=tags %}
        </div>

    </div>

{% endblock body %}

templates/notes/newtag.html
<div class="card">
    <h5 class="card-header">{% if tag %} Изменение тега {% else %} Создание нового тега {% endif %}</h5>
    <div class="card-body">

        <form class="well contact-form" method="post" action="{% url 'notes:addtag' %}">
            {% csrf_token %}

            <label for="tag_edit">Тег:</label>
            <input type="text" name="label" maxlength="200" id="tag_edit" value="{{ tag.label }}">


            <button type='submit' class='btn btn-primary btn-lg btn-block mt-2'>
                {% if tag %}
                    Изменить тег
                {% else %}
                    Создать тег
                {% endif %}
            </button>
        </form>

    </div>
</div>

{# временно убираю возможность удаления тега. Не придумал, куда прикрутить #}
{#{% if tag %}#}
{#    <div class="col-md-12" style="padding-top:15px">#}
{#        <form action="" method="POST">{% csrf_token %}#}
{#            <input type="hidden" name="control" value="delete"/>#}
{#            <input type="submit" value="Удалить метку" class="btn btn-lg btn-block btn-danger"/>#}
{#        </form>#}
{#    </div>#}
{#{% endif %}#}

templates/notes/notelist.html
{# выводим список заметок #}

    {% include 'notes/notes_paginator.html' with notes=notes page_obj=page_obj %}

{% for note in notes %}

    <div class="card mb-4">
        <h5 class="card-header">{{ note.label }}</h5>
        <div class="card-body">
            <p class="card-text text-truncate">{{ note.body }}</p>
            <small class="text-muted">{{ note.timestamp|date:"Дата: d E Y в H:i:s" }}</small>
        </div>
        <div class="card-footer text-muted">
            <div class="row">
                <div class="col-md-9">
                    {% if note.tags %}
                        <small class="text-muted">Теги:</small>
                        {% for tag in note.tags.all %}
                            <small class="text-muted"><a
                                    href="{% url 'notes:tagsearch' id=tag.id %}">{{ tag }}</a>
                            </small>
                            {% if not forloop.last %}
                                |
                            {% endif %}
                        {% endfor %}
                    {% endif %}
                </div>
                <div class="col-md-3">
                    <div class="text-right">
                        <small>
                            <a href="{% url 'notes:addnote' %}?id={{ note.id }}">
                                Редактировать заметку</a>
                        </small>
                    </div>
                </div>
            </div>
        </div>
    </div>

{% endfor %}

{% include 'notes/notes_paginator.html' with notes=notes %}

templates/notes/notes_paginator.html
<div class="pagination mt-1 mb-4 centering">
    <span class="step-links centering">
        {% if notes.has_previous %}
            <a href="?page=1" class="btn btn-outline-info">в начало</a>
            <a href="?page={{ notes.previous_page_number }}" class="btn btn-outline-info">предыдущая</a>
        {% endif %}

        {% for num in notes.paginator.page_range %}
            {% if num == notes.number %}
                <button class="btn btn-info">{{ num }}</button>
            {% elif num > notes.number|add:'-3' and num < notes.number|add:'3' %}
                <a href="?page={{ num }}" class="btn btn-outline-info">{{ num }}</a>
            {% endif %}
        {% endfor %}

        {% if notes.has_next %}
            <a href="?page={{ notes.next_page_number }}" class="btn btn-outline-info">следующая</a>
            <a href="?page={{ notes.paginator.num_pages }}" class="btn btn-outline-info">в конец</a>
        {% endif %}
    </span>
</div>

templates/notes/taglist.html
{# выводим список тегов #}

<div class="alert alert-info text-center" role="alert">
    <h1>Теги</h1>
</div>

<ul>
    {% if tags %}
        {% for tag in tags %}
            <li><a href="{% url 'notes:tagsearch' id=tag.id %}">{{ tag }}</a></li>
        {% endfor %}
    {% else %}
        <div class='alert alert-warning'>Теги не созданы</div>
    {% endif %}
</ul>

templates/notes/tagsearch.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
    DjNote. {{ title }}
{% endblock title %}

{% block body %}

    <div class="alert alert-primary text-center" role="alert">
        <h1>{{ title }}</h1>
    </div>

    {% if notes %}

        {% include 'notes/notelist.html' with notes=notes %}

    {% else %}

        <div class='alert alert-warning' align='center'>
            <h3>Нет заметок с выбранным тегом!</h3>
        </div>

    {% endif %}



{% endblock body %}